name: release master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: install dependencies
        run: npm install
      - name: install vsce
        run: sudo npm install -g vsce
      - name: extract version number
        run: |
          export BUILD_VERSION=$(grep version package.json | awk -F \" '{print $4}')
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      - name: package the extension
        run: vsce package
      - name: release package to github repo
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: master-${{ env.BUILD_VERSION }}
          prerelease: true
          title: 'Json to Dart Extension master-v${{ env.BUILD_VERSION }}'
          files: |
            ./json-to-dart-${{ env.BUILD_VERSION }}.vsix
